format_version: 2
environments:
  ci:
    pipelines:
      - "bootcamp"
      
pipelines:
  "bootcamp":
    group: team1
    materials:
      ui:
        git: "git@github.com:balabarath/cricket-scorer-api.git"
    stages:
      - buildAndTest:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/build/build.sh bootcamp

      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/deploy/deploy.sh bootcamp sethu-ec2-key-pair
