server:
 port: 9090

spring:
  datasource:
    url: jdbc:h2:./prodDb
    username: user
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true