UPDATE  GAME SET TEAM1_SCORE = 0 WHERE TEAM1_SCORE IS NULL;
UPDATE  GAME SET TEAM2_SCORE = 0 WHERE TEAM2_SCORE IS NULL;
UPDATE  GAME SET TEAM1_OVERS = 0 WHERE TEAM1_OVERS IS NULL;
UPDATE  GAME SET TEAM2_OVERS = 0 WHERE TEAM2_OVERS IS NULL;
UPDATE  GAME SET TEAM1_WICKETS = 0 WHERE TEAM1_WICKETS IS NULL;
UPDATE  GAME SET TEAM2_WICKETS = 0 WHERE TEAM2_WICKETS IS NULL;



ALTER TABLE GAME ALTER COLUMN TEAM1_SCORE SET DEFAULT 0    ;
ALTER TABLE GAME ALTER COLUMN TEAM2_SCORE   SET DEFAULT 0  ;
ALTER TABLE GAME ALTER COLUMN TEAM1_OVERS   SET DEFAULT 0  ;
ALTER TABLE GAME ALTER COLUMN TEAM2_OVERS   SET DEFAULT 0  ;
ALTER TABLE GAME ALTER COLUMN TEAM1_WICKETS SET DEFAULT 0  ;
ALTER TABLE GAME ALTER COLUMN TEAM2_WICKETS   SET DEFAULT 0;

ALTER TABLE GAME ALTER COLUMN TEAM1_SCORE   SET NOT NULL  ;
ALTER TABLE GAME ALTER COLUMN TEAM2_SCORE   SET NOT NULL ;
ALTER TABLE GAME ALTER COLUMN TEAM1_OVERS   SET NOT NULL  ;
ALTER TABLE GAME ALTER COLUMN TEAM2_OVERS   SET NOT NULL  ;
ALTER TABLE GAME ALTER COLUMN TEAM1_WICKETS SET NOT NULL  ;
ALTER TABLE GAME ALTER COLUMN TEAM2_WICKETS   SET NOT NULL;